create table
  public.profile (
    id bigint generated by default as identity,
    created_at timestamp with time zone not null default now(),
    age integer null default 21,
    height integer null default 70,
    weight integer null default 150,
    goal integer null default 0,
    exercise real null default '1.55'::real,
    user_id uuid,
    tdee integer null default 2000,
    bmr integer null default 2000,
    constraint profile_pkey primary key (id)
  ) tablespace pg_default;