create table
  public.steps (
    id bigint generated by default as identity,
    created_at timestamp with time zone not null default now(),
    value integer null,
    "startDate" date null,
    "endDate" date null,
    duration time without time zone null,
    type text null,
    constraint Steps_pkey primary key (id)
  ) tablespace pg_default;