create table
  public.sleep (
    id bigint generated by default as identity,
    created_at timestamp with time zone null default now(),
    "startDate" text null,
    "endDate" text null,
    value text null,
    duration text null,
    constraint sleep_pkey primary key (id)
  ) tablespace pg_default;